#!/usr/bin/env bash
# Reproduces the entire Task 4 pipeline from scratch, in order.
# Every file in results/ and models/ can be regenerated by running this.
set -e
cd "$(dirname "$0")"

echo "== 1/6 Generating interaction log data =="
python3 src/generate_data.py

echo "== 2/6 Training + evaluating the ranking model =="
python3 src/train_model.py

echo "== 3/6 Starting serving app =="
rm -f results/served_features.jsonl
(python3 src/serving_app.py > /tmp/serving.log 2>&1 &)
sleep 1.5

echo "== 4/6 Running load test (live HTTP calls, 11 concurrency levels) =="
python3 src/load_test.py --url http://127.0.0.1:8877/rank \
  --out results/load_test_results.csv --duration 3 \
  --levels 1,2,4,8,16,24,32,48,64,96,128

echo "== 5/6 Running failure-injection demo =="
python3 src/failure_demo.py

echo "Stopping serving app"
pkill -f serving_app.py || true
sleep 0.5

echo "== 6/6 Analyzing results (latency curve + breaking point + skew check) =="
python3 src/analyze_results.py
python3 src/skew_check.py

echo
echo "Done. See results/ and models/ for all generated evidence."
