"""
generate_logs.py
================
Simulates PlaceMux job-candidate matching logs the way a real marketplace
would produce them: a heuristic ranker serves candidates for each job,
candidates are shown in a list (impressions), and downstream behaviour
(click / apply / shortlist) is generated by a hidden "true relevance" plus
a position/examination-bias process (Position-Based Model: P(examine|pos)
= 1/pos^eta). This is the standard synthetic-LTR-with-bias setup used in
counterfactual-LTR literature (Joachims et al., Agarwal et al.).

We ALSO log a small randomized-order slice of traffic (RANDOM_FRACTION of
jobs) -- this is what real teams do ("intervention harvesting") to be able
to estimate true examination propensities later in position_bias.py.

Ground-truth relevance is kept in the output ONLY for offline evaluation
in this exercise (a real production system would never have it) --
clearly flagged as `true_relevance`.
"""
import numpy as np
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

RNG = np.random.default_rng(42)

N_JOBS = 1200
CANDS_PER_JOB = 20
POSITION_BIAS_ETA = 1.4          # examination decays as 1/pos^eta
RANDOM_FRACTION = 0.10            # 10% of jobs get randomized order (A/B slice)


def _sample_candidate_features(n):
    skill_match = RNG.beta(2, 2, n)
    experience_match = RNG.beta(2, 2, n)
    embedding_sim = np.clip(RNG.normal(0.55, 0.2, n), 0, 1)
    recency = RNG.beta(3, 2, n)
    past_response_rate = RNG.beta(2, 3, n)
    profile_completeness = RNG.beta(4, 2, n)
    return pd.DataFrame({
        "skill_match": skill_match,
        "experience_match": experience_match,
        "embedding_sim": embedding_sim,
        "recency": recency,
        "past_response_rate": past_response_rate,
        "profile_completeness": profile_completeness,
    })


def _true_relevance(feat: pd.DataFrame) -> np.ndarray:
    """Hidden ground truth the marketplace is actually trying to serve.
    Note: recency & profile_completeness carry NO true signal -- they are
    purely cosmetic/spurious, on purpose (see _heuristic_score)."""
    score = (
        0.40 * feat.skill_match
        + 0.30 * feat.experience_match
        + 0.20 * feat.embedding_sim
        + 0.10 * feat.past_response_rate
    )
    score = score + RNG.normal(0, 0.04, len(feat))
    return np.clip(score, 0, 1)


def _heuristic_score(feat: pd.DataFrame) -> np.ndarray:
    """The CURRENT production heuristic -- deliberately mis-weighted vs
    true relevance: over-indexes on recency & profile completeness (which
    carry ZERO true signal) and under-indexes on skill/experience (which
    drive real outcomes), and ignores past_response_rate entirely. This is
    exactly how real hand-tuned heuristics drift over time."""
    return (
        0.15 * feat.skill_match
        + 0.10 * feat.experience_match
        + 0.15 * feat.embedding_sim
        + 0.35 * feat.recency
        + 0.25 * feat.profile_completeness
    )


def generate(n_jobs=N_JOBS, cands_per_job=CANDS_PER_JOB):
    rows = []
    n_random_jobs = int(n_jobs * RANDOM_FRACTION)
    randomized_job_ids = set(RNG.choice(n_jobs, n_random_jobs, replace=False).tolist())

    for job_id in range(n_jobs):
        feat = _sample_candidate_features(cands_per_job)
        feat["true_relevance"] = _true_relevance(feat)
        feat["heuristic_score"] = _heuristic_score(feat)
        is_randomized_slice = job_id in randomized_job_ids

        if is_randomized_slice:
            order = RNG.permutation(cands_per_job)
        else:
            order = np.argsort(-feat["heuristic_score"].values)

        for pos, cand_idx in enumerate(order, start=1):
            r = feat.iloc[cand_idx]
            examine_prob = 1.0 / (pos ** POSITION_BIAS_ETA)
            examined = RNG.random() < examine_prob
            click = apply_ = shortlist = 0
            if examined:
                click_prob = 0.05 + 0.55 * r.true_relevance
                click = int(RNG.random() < click_prob)
                if click:
                    applied_prob = 0.10 + 0.55 * r.true_relevance
                    apply_ = int(RNG.random() < applied_prob)
                    if apply_:
                        shortlist_prob = 0.10 + 0.6 * r.true_relevance
                        shortlist = int(RNG.random() < shortlist_prob)

            rows.append({
                "job_id": job_id,
                "candidate_idx": cand_idx,
                "position": pos,
                "is_randomized_slice": int(is_randomized_slice),
                "skill_match": r.skill_match,
                "experience_match": r.experience_match,
                "embedding_sim": r.embedding_sim,
                "recency": r.recency,
                "past_response_rate": r.past_response_rate,
                "profile_completeness": r.profile_completeness,
                "region_group": RNG.choice(["A", "B", "C"], p=[0.5, 0.3, 0.2]),
                "examined": int(examined),
                "click": click,
                "applied": apply_,
                "shortlist": shortlist,
                "true_relevance": r.true_relevance,       # simulator-only, for eval
                "heuristic_score": r.heuristic_score,
            })

    df = pd.DataFrame(rows)
    df["outcome_label"] = df["click"] + 3 * df["applied"] + 5 * df["shortlist"]
    return df


if __name__ == "__main__":
    df = generate()
    df.to_csv(ROOT / "data" / "raw_logs.csv", index=False)
    print(f"Generated {len(df)} logged impressions across {df.job_id.nunique()} jobs.")
    print(f"Randomized-order slice: {df.is_randomized_slice.mean()*100:.1f}% of impressions.")
    print(f"Overall CTR: {df.click.mean():.3f} | Apply rate: {df.applied.mean():.3f} | Shortlist rate: {df.shortlist.mean():.3f}")
