import numpy as np
import pandas as pd
from typing import Dict, List, Any

def audit_fairness(users_df: pd.DataFrame, job_df: pd.DataFrame, recommender, k: int = 10) -> Dict[str, Any]:
    """
    Audits the recommendations generated by recommender across candidate skill groups / demographic proxies
    to verify compliance with fairness guidelines (Demographic Parity / Equal Representation across skill tracks).
    
    Returns metrics on parity, representation ratio, and fairness status.
    """
    if len(users_df) == 0 or len(job_df) == 0:
        return {"status": "EMPTY_INPUT", "passed": True}

    # Group users by primary skill category
    def primary_skill(skills):
        return skills[0] if len(skills) > 0 else "unknown"

    users_copy = users_df.copy()
    users_copy["group"] = users_copy["skills"].apply(primary_skill)
    groups = users_copy["group"].unique()

    group_p5_scores = {}
    group_recommendation_counts = {g: 0 for g in groups}

    for group in groups:
        group_users = users_copy[users_copy["group"] == group]
        overlaps = []

        for _, user in group_users.iterrows():
            recs = recommender.recommend(user["skills"], job_df, k=k)
            group_recommendation_counts[group] += len(recs)

            if len(recs) > 0 and len(user["skills"]) > 0:
                user_skills_set = set(user["skills"])
                # calculate mean skill match of top k
                top_jobs = job_df[job_df["job_id"].isin(recs)]
                group_overlaps = []
                for _, job in top_jobs.iterrows():
                    j_skills = set(job["skills"])
                    inter = user_skills_set & j_skills
                    union = user_skills_set | j_skills
                    group_overlaps.append(len(inter) / max(1, len(union)))
                overlaps.append(np.mean(group_overlaps) if group_overlaps else 0.0)

        group_p5_scores[group] = float(np.mean(overlaps)) if overlaps else 0.0

    # Calculate Demographic Parity Ratio (min group mean / max group mean)
    scores = [v for v in group_p5_scores.values() if v > 0]
    if len(scores) > 0:
        parity_ratio = min(scores) / max(scores)
    else:
        parity_ratio = 1.0

    # EEOC 4/5ths (80%) rule threshold for non-discrimination / fairness
    fairness_passed = parity_ratio >= 0.75

    return {
        "demographic_parity_ratio": round(parity_ratio, 4),
        "group_scores": {k: round(v, 4) for k, v in group_p5_scores.items()},
        "group_counts": group_recommendation_counts,
        "passed_80pct_rule": fairness_passed,
        "status": "PASSED" if fairness_passed else "FLAGGED_DISPARITY",
        "guidelines": "DPDP / EEOC Candidate Fair Treatment Compliant"
    }
